export const EVENTS_STORE_DB_CONNECTION_NAME = 'EVENTS_STORE_DB_CONNECTION';
export const SHARED_DB_CONNECTION_NAME = 'SHARED_DB_CONNECTION';
export const EVENTS_STORE_DB_NAME = 'EVENTS_STORE_DB_NAME';
export const SHARED_DB_NAME = 'SHARED_DB_NAME';
export const MONGO_SERVER_URL = 'MONGO_SERVER_URL';
