export const EVENTS_STORE_DB_CONNECTION_NAME = 'EVENTS_STORE_DB_CONNECTION';
export const EVENTS_STORE_DB_NAME = 'EVENTS_STORE_DB_NAME';
export const EVENT_STORE_SERVER_URL = 'EVENT_STORE_SERVER_URL';
