export enum CommandSocketEventsEnum {
  SEND_MESSAGE = 'SEND_MESSAGE',
  ADD_USER_TO_ROOM = 'ADD_USER_TO_ROOM',
  USER_LEFT_ROOM = 'USER_LEFT_ROOM',
  CREATE_MEETUP = 'CREATE_MEETUP',
  CHANGE_RSVP = 'CHANGE_RSVP',
  CREATE_POLL = 'CREATE_POLL',
  POLL_VOTE = 'POLL_VOTE',
  CLOSE_POLL = 'CLOSE_POLL',
  CLOSED_ROOM = 'CLOSED_ROOM',
  CREATE_ROOM = 'CREATE_ROOM'
}
