export enum WebsocketEventsEnum {
  ACTIVE_USER_LIST = 'ACTIVE_USER_LIST',
  ALL_USERS = 'ALL_USERS',
  ROOM_LIST = 'ROOM_LIST',
  MEETUP_LIST = 'MEETUP_LIST',
  ROOM_CREATED = 'ROOM_CREATED',
  NEW_ROOM_ITEM = 'NEW_ROOM_ITEM',
  NEW_MEETUP = 'NEW_MEETUP',
  RSVP_CHANGED = 'RSVP_CHANGED',
  POLL_CREATED = 'POLL_CREATED',
  POLL_VOTE = 'POLL_VOTE',
  POLL_CLOSED = 'POLL_CLOSED',
  NOTIFICATION = 'NOTIFICATION'
}
